env:
  global:
    - CABALVER=1.22
    - PACKAGE_LIST="./monad-logger ./wai-logger ./fast-logger"
  matrix:
    - GHCVER=7.6.3
    - GHCVER=7.8.4
    - GHCVER=7.10.3
    - GHCVER=head

matrix:
  allow_failures:
    # GHC head cannot not compile QuickCheck at this moment.
    - env: GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

script:
 # First install all packages with dependencies. Have to jump through these
 # hoops because of problems with wai-extra, see:
 # https://github.com/kazu-yamamoto/logger/issues/42
 - cabal install --enable-tests --enable-benchmarks --force-reinstalls --reorder-goals --max-backjumps=-1 wai-extra $PACKAGE_LIST
 - cabal install --run-tests --force-reinstalls $PACKAGE_LIST
